#############################################################################
# Makefile for building: GuiPFC
# Generated by qmake (2.01a) (Qt 4.7.2) on: mar jul 5 19:04:50 2011
# Project:  GuiPFC.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile GuiPFC.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = btcomm.cpp \
		cppview.cpp \
		guiapp.cpp \
		handtracking.cpp \
		mykinect.cpp moc_guiapp.cpp
OBJECTS       = btcomm.o \
		cppview.o \
		guiapp.o \
		handtracking.o \
		mykinect.o \
		moc_guiapp.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		GuiPFC.pro
QMAKE_TARGET  = GuiPFC
DESTDIR       = 
TARGET        = GuiPFC

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_guiapp.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GuiPFC.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile GuiPFC.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile GuiPFC.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GuiPFC1.0.0 || $(MKDIR) .tmp/GuiPFC1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GuiPFC1.0.0/ && $(COPY_FILE) --parents btcomm.hpp guiapp.hpp handdetection.hpp handtracking.hpp libfreenect.hpp mykinect.hpp /usr/include/libfreenect.h .tmp/GuiPFC1.0.0/ && $(COPY_FILE) --parents btcomm.cpp cppview.cpp guiapp.cpp handtracking.cpp mykinect.cpp .tmp/GuiPFC1.0.0/ && $(COPY_FILE) --parents guiapp.ui .tmp/GuiPFC1.0.0/ && (cd `dirname .tmp/GuiPFC1.0.0` && $(TAR) GuiPFC1.0.0.tar GuiPFC1.0.0 && $(COMPRESS) GuiPFC1.0.0.tar) && $(MOVE) `dirname .tmp/GuiPFC1.0.0`/GuiPFC1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GuiPFC1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_guiapp.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_guiapp.cpp
moc_guiapp.cpp: libfreenect.hpp \
		/usr/include/libfreenect.h \
		btcomm.hpp \
		mykinect.hpp \
		handtracking.hpp \
		guiapp.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) guiapp.hpp -o moc_guiapp.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_guiapp.h
compiler_uic_clean:
	-$(DEL_FILE) ui_guiapp.h
ui_guiapp.h: guiapp.ui
	/usr/bin/uic-qt4 guiapp.ui -o ui_guiapp.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

btcomm.o: btcomm.cpp btcomm.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o btcomm.o btcomm.cpp

cppview.o: cppview.cpp libfreenect.hpp \
		/usr/include/libfreenect.h \
		btcomm.hpp \
		mykinect.hpp \
		handtracking.hpp \
		guiapp.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cppview.o cppview.cpp

guiapp.o: guiapp.cpp guiapp.hpp \
		libfreenect.hpp \
		/usr/include/libfreenect.h \
		btcomm.hpp \
		mykinect.hpp \
		handtracking.hpp \
		ui_guiapp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiapp.o guiapp.cpp

handtracking.o: handtracking.cpp handtracking.hpp \
		handdetection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handtracking.o handtracking.cpp

mykinect.o: mykinect.cpp mykinect.hpp \
		libfreenect.hpp \
		/usr/include/libfreenect.h \
		btcomm.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mykinect.o mykinect.cpp

moc_guiapp.o: moc_guiapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guiapp.o moc_guiapp.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

